// ─────────────────────────────────────────────────────────────────
// Templates Data Layer — Multi-Category & Lifecycle System
// ─────────────────────────────────────────────────────────────────
import type { TemplateStatus } from "@/types/category.types";

export interface TemplateSpec {
  id: string;
  name: string;
  category: string; // Primary Category Slug (e.g. "love", "raksha-bandhan", "birthday")
  categoryName: string; // Human readable category name (e.g. "Love", "Raksha Bandhan")
  subCategory?: string; // Optional sub-style (e.g. "Cosmic Romance", "Classic Editorial")
  description: string;
  thumbnail: string;
  vibe: string;
  atmosphere: string;
  status: TemplateStatus; // Lifecycle Status (draft | development | review | testing | ready | published | archived)
  badge?: "Popular" | "New" | "Featured";
  tags: string[];
  setupTime: string; // e.g. "2 mins"
  perfectFor: string;
  features: string[];
  pagesIncluded: number;
  animations: string;
  performanceScore: number; // e.g. 99
  aiReady: boolean;
  responsive: boolean;
  seoReady: boolean;
  darkMode: boolean;
}

export const TEMPLATES_DATA: Record<string, TemplateSpec> = {
  // ═════════════════════════════════════════════════════════════════
  // LOVE COLLECTION (10 Original Handcrafted Templates — PUBLISHED)
  // ═════════════════════════════════════════════════════════════════
  cosmic: {
    id: "cosmic",
    name: "Cosmic Love",
    category: "love",
    categoryName: "Love",
    subCategory: "Cosmic Romance",
    description: "Deep obsidian shadows punctuated by stardust particle FX and champagne gold highlights.",
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    vibe: "Deep Obsidian & Starlight",
    atmosphere: "A surreal blend of starlight and intimate warmth.",
    status: "published",
    badge: "Popular",
    tags: ["Starlight FX", "Obsidian Dark", "Champagne Gold", "Particle Canvas"],
    setupTime: "2 mins",
    perfectFor: "Surreal stargazers & deep intimacy lovers",
    features: ["Starlight Canvas Particles", "Cinematic Loader", "Audio Music Player", "Interactive Timeline"],
    pagesIncluded: 4,
    animations: "GPU Particle Physics",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  memories: {
    id: "memories",
    name: "Forever Memories",
    category: "love",
    categoryName: "Love",
    subCategory: "Classic Editorial",
    description: "Warm amber tones, like candlelight through old editorial photographs and heirloom frames.",
    thumbnail: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
    vibe: "Classic Editorial Elegance",
    atmosphere: "Warm amber tones, like candlelight through old photographs.",
    status: "published",
    badge: "Featured",
    tags: ["Vintage Amber", "Film Grain", "Polaroid Grid", "Editorial Serif"],
    setupTime: "2 mins",
    perfectFor: "Anniversaries & nostalgic photo collections",
    features: ["Polaroid Gallery", "Warm Amber Lighting", "Heirloom Typography", "Audio Player"],
    pagesIncluded: 4,
    animations: "Smooth Lenis Scroll",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  rose: {
    id: "rose",
    name: "Rose Garden",
    category: "love",
    categoryName: "Love",
    subCategory: "Vintage Romance",
    description: "Velvet burgundy petals floating gently over timeless love letter typography.",
    thumbnail: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80",
    vibe: "Muted Burgundy & Vintage",
    atmosphere: "Velvet petals and vintage romance. The colour of love letters.",
    status: "published",
    badge: "Popular",
    tags: ["Rose Petals", "Velvet Burgundy", "Love Letters", "Serif Typography"],
    setupTime: "2 mins",
    perfectFor: "Romantic proposals & secret love letters",
    features: ["Floating Petal Animation", "Love Letter Canvas", "Burgundy Glow", "Timeline Milestones"],
    pagesIncluded: 4,
    animations: "Floating Petal Particles",
    performanceScore: 97,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  dream: {
    id: "dream",
    name: "Dream Universe",
    category: "love",
    categoryName: "Love",
    subCategory: "Ethereal Dream",
    description: "Surreal electric blue haze and pastel violet gradients for a dreamlike memory haze.",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    vibe: "Ethereal Pastels & Haze",
    atmosphere: "Surreal and electric. Like a dream you never want to leave.",
    status: "published",
    badge: "New",
    tags: ["Electric Blue", "Violet Gradients", "Glassmorphism", "Surreal Haze"],
    setupTime: "2 mins",
    perfectFor: "Modern couples & surreal memory boxes",
    features: ["Aurora Haze Canvas", "Glass Cards", "Glow Effects", "Full Video Hero"],
    pagesIncluded: 4,
    animations: "Aurora Fluid Waves",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  cinematic: {
    id: "cinematic",
    name: "Cinematic Story",
    category: "love",
    categoryName: "Love",
    subCategory: "Cinematic Film",
    description: "Shot like a classic noir film with letterbox framing, spotlights, and high-contrast visuals.",
    thumbnail: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80",
    vibe: "Film Noir & High Contrast",
    atmosphere: "Shot like a classic film. Every frame worthy of a cinema screen.",
    status: "published",
    badge: "Featured",
    tags: ["Film Noir", "High Contrast", "Letterbox Frame", "Cinema Spotlights"],
    setupTime: "3 mins",
    perfectFor: "Film enthusiasts & dramatic love stories",
    features: ["Cinematic Letterboxing", "Film Grain Overlay", "Full Video Integration", "Masonry Gallery"],
    pagesIncluded: 5,
    animations: "Camera Lens Zoom",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  proposal: {
    id: "proposal",
    name: "Proposal Special",
    category: "love",
    categoryName: "Love",
    subCategory: "Luxury Proposal",
    description: "Intimate champagne, warm candlelight, and an interactive proposal card for the big moment.",
    thumbnail: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80",
    vibe: "Intimate & Luxurious",
    atmosphere: "Champagne, candlelight, and forever. The most important moment.",
    status: "published",
    badge: "Popular",
    tags: ["Proposal Ring", "Champagne Gold", "Candlelight", "Interactive Card"],
    setupTime: "2 mins",
    perfectFor: "Marriage proposals & grand romantic declarations",
    features: ["Interactive Proposal Card", "Champagne Sparkle FX", "Custom Countdown", "Background Audio"],
    pagesIncluded: 4,
    animations: "Ring Sparkle FX",
    performanceScore: 100,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  moonlight: {
    id: "moonlight",
    name: "Moonlight Promise",
    category: "love",
    categoryName: "Love",
    subCategory: "Sapphire Night",
    description: "Midnight sapphire sky with glowing silver moonlight and celestial constellation particles.",
    thumbnail: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80",
    vibe: "Midnight Sapphire & Silver Glow",
    atmosphere: "A quiet midnight under glowing constellations and silver moonlight.",
    status: "published",
    badge: "New",
    tags: ["Sapphire Blue", "Silver Moonlight", "Constellations", "Glowing Stars"],
    setupTime: "2 mins",
    perfectFor: "Night lovers & quiet romantic promises",
    features: ["Silver Moon FX", "Constellation Canvas", "Sapphire Gradient", "Interactive Story"],
    pagesIncluded: 4,
    animations: "Twinkling Constellations",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  golden: {
    id: "golden",
    name: "Golden Vows",
    category: "love",
    categoryName: "Love",
    subCategory: "Regal Gold",
    description: "Opulent gold foil accents and timeless royal wedding editorial typography.",
    thumbnail: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    vibe: "Gilded Ivory & Regal Serif",
    atmosphere: "Opulent gold foil accents and timeless royal wedding elegance.",
    status: "published",
    badge: "Featured",
    tags: ["Regal Gold", "Gilded Foil", "Ivory Accents", "Serif Typography"],
    setupTime: "2 mins",
    perfectFor: "Weddings, vows & golden jubilees",
    features: ["Gold Dust Particles", "Gilded Borders", "Vow Section", "Full Photo Gallery"],
    pagesIncluded: 4,
    animations: "Gold Shimmer Physics",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  sakura: {
    id: "sakura",
    name: "Sakura Bloom",
    category: "love",
    categoryName: "Love",
    subCategory: "Cherry Blossom",
    description: "Gentle pink petals floating through spring breezes and warm pearl sunlight.",
    thumbnail: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=800&q=80",
    vibe: "Soft Cherry Blossom & Pearl",
    atmosphere: "Gentle pink petals floating through spring breezes and warm sunlight.",
    status: "published",
    badge: "New",
    tags: ["Cherry Blossom", "Sakura Petals", "Soft Pink", "Pearl Warmth"],
    setupTime: "2 mins",
    perfectFor: "Spring romance & soft aesthetic memories",
    features: ["Floating Sakura Petals", "Soft Pink Canvas", "Poetry Cards", "Audio Track"],
    pagesIncluded: 4,
    animations: "Sakura Petal Breeze",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  eternal: {
    id: "eternal",
    name: "Eternal Hearts",
    category: "love",
    categoryName: "Love",
    subCategory: "Crimson Passion",
    description: "Deep crimson waves and glowing heartbeat pulses that celebrate everlasting passion.",
    thumbnail: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
    vibe: "Deep Crimson & Radiant Ruby",
    atmosphere: "Passionate crimson waves and glowing heartbeats that last forever.",
    status: "published",
    badge: "Popular",
    tags: ["Deep Crimson", "Heartbeat Pulse", "Ruby Red", "Romantic Cards"],
    setupTime: "2 mins",
    perfectFor: "Passionate lovers & milestone celebrations",
    features: ["Heartbeat Pulse FX", "Crimson Glow", "Love Timeline", "Music Player"],
    pagesIncluded: 4,
    animations: "Pulse Heartbeat Wave",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },

  // ═════════════════════════════════════════════════════════════════
  // RAKSHA BANDHAN COLLECTION (6 Flagship Masterpiece Templates)
  // ═════════════════════════════════════════════════════════════════
  "rakhi-bond": {
    id: "rakhi-bond",
    name: "The Purest Bond Ever",
    category: "raksha-bandhan",
    categoryName: "Raksha Bandhan",
    subCategory: "Sacred Bond",
    description: "Golden sacred thread animations, childhood throwback photo frames, and documentary storytelling.",
    thumbnail: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80",
    vibe: "Golden Saffron & Sacred Silk",
    atmosphere: "Celebrating a bond tied with love, protection, and lifelong laughter.",
    status: "published",
    badge: "Featured",
    tags: ["Sacred Thread", "Brother Sister", "Saffron Gold", "Documentary"],
    setupTime: "2 mins",
    perfectFor: "Celebrating brother & sister love on Raksha Bandhan",
    features: ["Rakhi Thread Animation", "Saffron Glow Canvas", "Childhood Timeline", "Custom Audio Blessing"],
    pagesIncluded: 4,
    animations: "Golden Thread Weave",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  "rakhi-threads": {
    id: "rakhi-threads",
    name: "Threads of Love",
    category: "raksha-bandhan",
    categoryName: "Raksha Bandhan",
    subCategory: "Handcrafted Scrapbook",
    description: "Handcrafted scrapbook aesthetic with deckled paper edges, polaroid memories, and marigold silk accents.",
    thumbnail: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80",
    vibe: "Marigold Yellow & Crimson Silk",
    atmosphere: "Warm, festive, and glowing with childhood memories.",
    status: "published",
    badge: "Popular",
    tags: ["Handcrafted Scrapbook", "Marigold Glow", "Polaroid Tilt", "Deckled Paper"],
    setupTime: "2 mins",
    perfectFor: "Sending virtual Rakhi gifts and photo scrapbooks",
    features: ["Interactive Rakhi Card", "Confetti Sparkles", "Gift Card Integration", "Music Soundtrack"],
    pagesIncluded: 4,
    animations: "Festive Sparkle Waves",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  "rakhi-childhood": {
    id: "rakhi-childhood",
    name: "Our Childhood",
    category: "raksha-bandhan",
    categoryName: "Raksha Bandhan",
    subCategory: "Nostalgic Journey",
    description: "Retro film layout designed to showcase silly childhood fights, shared secrets, and growing up together.",
    thumbnail: "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=800&q=80",
    vibe: "Nostalgic Polaroid & Warm Sepia",
    atmosphere: "Reliving every silly secret, shared ice cream, and childhood memory.",
    status: "published",
    badge: "New",
    tags: ["Childhood Fights", "Retro Polaroid", "Secret Notes", "Sibling Story"],
    setupTime: "2 mins",
    perfectFor: "Sibling nostalgia & childhood memories",
    features: ["Polaroid Film Stack", "Audio Storytelling", "Secret Memory Notes", "Shareable Video"],
    pagesIncluded: 4,
    animations: "Film Slide Physics",
    performanceScore: 97,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  "rakhi-miles": {
    id: "rakhi-miles",
    name: "Miles Apart, Hearts Together",
    category: "raksha-bandhan",
    categoryName: "Raksha Bandhan",
    subCategory: "Long Distance",
    description: "Designed for siblings living across different cities or countries to celebrate Rakhi virtually.",
    thumbnail: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80",
    vibe: "Celestial Map & Midnight Gold",
    atmosphere: "Distance means nothing when hearts are bound by love.",
    status: "published",
    badge: "Featured",
    tags: ["Long Distance", "Miles Apart", "Virtual Route Map", "Global Connection"],
    setupTime: "2 mins",
    perfectFor: "Siblings celebrating Rakhi across long distances",
    features: ["Interactive Distance Map", "Virtual Rakhi Tying FX", "Video Message Hub", "Live Countdown"],
    pagesIncluded: 4,
    animations: "Constellation Connection",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  "rakhi-brother": {
    id: "rakhi-brother",
    name: "Dear Brother / Dear Sister",
    category: "raksha-bandhan",
    categoryName: "Raksha Bandhan",
    subCategory: "Luxury Editorial Letter",
    description: "An elegant, letterform tribute experience with unfolding paper presentation, ink text reveal, and wax seal.",
    thumbnail: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80",
    vibe: "Deep Royal Blue & Warm Gold",
    atmosphere: "A heartfelt love letter between brother and sister.",
    status: "published",
    badge: "Popular",
    tags: ["Editorial Letter", "Wax Seal", "Ink Reveal", "Protection Promise"],
    setupTime: "2 mins",
    perfectFor: "Heartfelt letters & promises between siblings",
    features: ["Heartfelt Letter Canvas", "Photo Slider", "Promise Card", "Background Soundtrack"],
    pagesIncluded: 4,
    animations: "Smooth Letter Reveal",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  "rakhi-sister": {
    id: "rakhi-sister",
    name: "Dear Sister",
    category: "raksha-bandhan",
    categoryName: "Raksha Bandhan",
    subCategory: "Brother's Gift",
    description: "Brother's digital gift website.",
    thumbnail: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80",
    vibe: "Rose Gold & Pearl White",
    atmosphere: "A brother's promise.",
    status: "archived",
    badge: "New",
    tags: ["Archived"],
    setupTime: "2 mins",
    perfectFor: "Legacy",
    features: [],
    pagesIncluded: 4,
    animations: "None",
    performanceScore: 90,
    aiReady: false,
    responsive: true,
    seoReady: false,
    darkMode: true,
  },
  "rakhi-promise": {
    id: "rakhi-promise",
    name: "Our Promise",
    category: "raksha-bandhan",
    categoryName: "Raksha Bandhan",
    subCategory: "Pledge",
    description: "Sacred promise cards.",
    thumbnail: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80",
    vibe: "Charcoal",
    atmosphere: "Pledge",
    status: "archived",
    badge: "New",
    tags: ["Archived"],
    setupTime: "2 mins",
    perfectFor: "Legacy",
    features: [],
    pagesIncluded: 4,
    animations: "None",
    performanceScore: 90,
    aiReady: false,
    responsive: true,
    seoReady: false,
    darkMode: true,
  },
  "rakhi-memories": {
    id: "rakhi-memories",
    name: "Forever Together",
    category: "raksha-bandhan",
    categoryName: "Raksha Bandhan",
    subCategory: "Documentary Masterpiece",
    description: "Flagship documentary masterpiece with chapter navigation, film progress, and A24-style credits ending.",
    thumbnail: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80",
    vibe: "Festive Amber & Warm Gold",
    atmosphere: "A documentary masterpiece celebrating everlasting togetherness.",
    status: "published",
    badge: "Popular",
    tags: ["Documentary Masterpiece", "Movie Credits", "Annual Timeline", "Photo Vault"],
    setupTime: "2 mins",
    perfectFor: "Flagship documentary storytelling for siblings",
    features: ["Year-by-Year Timeline", "Photo Masonry Grid", "Family Blessings", "Movie Credits Ending"],
    pagesIncluded: 5,
    animations: "Smooth Lenis Scroll",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },

  // ═════════════════════════════════════════════════════════════════
  // OTHER COLLECTIONS (In Development)
  // ═════════════════════════════════════════════════════════════════
  "bday-memories": {
    id: "bday-memories",
    name: "Birthday Memories",
    category: "birthday",
    categoryName: "Birthday",
    subCategory: "Celebration Hub",
    description: "High-energy birthday celebration portal featuring live confetti, surprise video reveals, and wish wall.",
    thumbnail: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80",
    vibe: "Electric Purple & Neon Gold",
    atmosphere: "Pure joy, laughter, and birthday sparkles.",
    status: "development",
    badge: "Popular",
    tags: ["Confetti FX", "Birthday Surprises", "Wish Wall", "Video Hub"],
    setupTime: "2 mins",
    perfectFor: "Birthday surprise websites & friend group gifts",
    features: ["Interactive Confetti FX", "Friend Wish Wall", "Surprise Video Player", "Countdown Timer"],
    pagesIncluded: 4,
    animations: "GPU Confetti Physics",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  "wedding-eternal": {
    id: "wedding-eternal",
    name: "Eternal Vows",
    category: "wedding",
    categoryName: "Wedding",
    subCategory: "Royal Luxury",
    description: "Regal ivory wedding website with RSVP manager, event schedule timeline, and guestbook.",
    thumbnail: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    vibe: "Gilded Ivory & Floral Elegance",
    atmosphere: "Classic romance, champagne toasts, and forever promises.",
    status: "development",
    badge: "Featured",
    tags: ["Wedding Site", "RSVP Form", "Itinerary", "Gilded Floral"],
    setupTime: "3 mins",
    perfectFor: "Weddings, bride & groom showcases, and RSVP tracking",
    features: ["RSVP Form Integration", "Interactive Event Schedule", "Gift Registry Link", "Photo Gallery"],
    pagesIncluded: 5,
    animations: "Floral Parallax Scroll",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: false,
  },
  "biz-startup": {
    id: "biz-startup",
    name: "Startup Landing",
    category: "startup",
    categoryName: "Startup",
    subCategory: "Tech Showcase",
    description: "High-impact tech landing page with animated feature cards, pricing table, and lead capture.",
    thumbnail: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80",
    vibe: "Dark Neon & Electric Cyan",
    atmosphere: "Cutting-edge innovation meets sleek software design.",
    status: "development",
    badge: "Popular",
    tags: ["Startup Landing", "SaaS Pricing", "Lead Capture", "Dark Tech"],
    setupTime: "2 mins",
    perfectFor: "App launches, SaaS products & tech startups",
    features: ["Interactive Feature Matrix", "Pricing Tier Cards", "Email Waitlist", "Live Demo Embed"],
    pagesIncluded: 4,
    animations: "Electric Mesh Glow",
    performanceScore: 100,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  "portfolio-creative": {
    id: "portfolio-creative",
    name: "Modern Creator Portfolio",
    category: "portfolio",
    categoryName: "Portfolio",
    subCategory: "Minimalist Grid",
    description: "Sleek dark portfolio designed for designers, developers, photographers, and creators.",
    thumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
    vibe: "Minimal Charcoal & Monochrone",
    atmosphere: "Let your work speak with high-impact typography and clean layouts.",
    status: "development",
    badge: "New",
    tags: ["Creator Portfolio", "Masonry Gallery", "Case Studies", "Contact Form"],
    setupTime: "2 mins",
    perfectFor: "Designers, photographers, developers & freelancers",
    features: ["Masonry Project Grid", "Case Study Modal", "Interactive Resume", "Direct Contact Form"],
    pagesIncluded: 4,
    animations: "Smooth Lenis Scroll",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
};

export const TEMPLATE_CATEGORIES = [
  "All",
  "Love",
  "Raksha Bandhan",
  "Birthday",
  "Wedding",
  "Portfolio",
  "Business",
  "Startup",
  "Resume",
  "SaaS",
  "Restaurant",
  "Education",
  "Festival",
];

export const TEMPLATE_LIST = Object.values(TEMPLATES_DATA);
