// ─────────────────────────────────────────────────────────────────
// Templates Data Layer — Rich metadata for 10 Handcrafted Templates
// ─────────────────────────────────────────────────────────────────

export interface TemplateSpec {
  id: string;
  name: string;
  category: string;
  description: string;
  thumbnail: string;
  vibe: string;
  atmosphere: string;
  badge?: "Popular" | "New" | "Featured";
  tags: string[];
  setupTime: string; // e.g. "2 mins"
  perfectFor: string;
  features: string[];
  pagesIncluded: number;
  animations: string;
  performanceScore: number; // e.g. 99
  aiReady: boolean;
  responsive: boolean;
  seoReady: boolean;
  darkMode: boolean;
}

export const TEMPLATES_DATA: Record<string, TemplateSpec> = {
  cosmic: {
    id: "cosmic",
    name: "Cosmic Love",
    category: "Cosmic Romance",
    description: "Deep obsidian shadows punctuated by stardust particle FX and champagne gold highlights.",
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    vibe: "Deep Obsidian & Starlight",
    atmosphere: "A surreal blend of starlight and intimate warmth.",
    badge: "Popular",
    tags: ["Starlight FX", "Obsidian Dark", "Champagne Gold", "Particle Canvas"],
    setupTime: "2 mins",
    perfectFor: "Surreal stargazers & deep intimacy lovers",
    features: ["Starlight Canvas Particles", "Cinematic Loader", "Audio Music Player", "Interactive Timeline"],
    pagesIncluded: 4,
    animations: "GPU Particle Physics",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  memories: {
    id: "memories",
    name: "Forever Memories",
    category: "Classic Editorial",
    description: "Warm amber tones, like candlelight through old editorial photographs and heirloom frames.",
    thumbnail: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
    vibe: "Classic Editorial Elegance",
    atmosphere: "Warm amber tones, like candlelight through old photographs.",
    badge: "Featured",
    tags: ["Vintage Amber", "Film Grain", "Polaroid Grid", "Editorial Serif"],
    setupTime: "2 mins",
    perfectFor: "Anniversaries & nostalgic photo collections",
    features: ["Polaroid Gallery", "Warm Amber Lighting", "Heirloom Typography", "Audio Player"],
    pagesIncluded: 4,
    animations: "Smooth Lenis Scroll",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  rose: {
    id: "rose",
    name: "Rose Garden",
    category: "Vintage Romance",
    description: "Velvet burgundy petals floating gently over timeless love letter typography.",
    thumbnail: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80",
    vibe: "Muted Burgundy & Vintage",
    atmosphere: "Velvet petals and vintage romance. The colour of love letters.",
    badge: "Popular",
    tags: ["Rose Petals", "Velvet Burgundy", "Love Letters", "Serif Typography"],
    setupTime: "2 mins",
    perfectFor: "Romantic proposals & secret love letters",
    features: ["Floating Petal Animation", "Love Letter Canvas", "Burgundy Glow", "Timeline Milestones"],
    pagesIncluded: 4,
    animations: "Floating Petal Particles",
    performanceScore: 97,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  dream: {
    id: "dream",
    name: "Dream Universe",
    category: "Ethereal Dream",
    description: "Surreal electric blue haze and pastel violet gradients for a dreamlike memory haze.",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    vibe: "Ethereal Pastels & Haze",
    atmosphere: "Surreal and electric. Like a dream you never want to leave.",
    badge: "New",
    tags: ["Electric Blue", "Violet Gradients", "Glassmorphism", "Surreal Haze"],
    setupTime: "2 mins",
    perfectFor: "Modern couples & surreal memory boxes",
    features: ["Aurora Haze Canvas", "Glass Cards", "Glow Effects", "Full Video Hero"],
    pagesIncluded: 4,
    animations: "Aurora Fluid Waves",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  cinematic: {
    id: "cinematic",
    name: "Cinematic Story",
    category: "Cinematic Film",
    description: "Shot like a classic noir film with letterbox framing, spotlights, and high-contrast visuals.",
    thumbnail: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80",
    vibe: "Film Noir & High Contrast",
    atmosphere: "Shot like a classic film. Every frame worthy of a cinema screen.",
    badge: "Featured",
    tags: ["Film Noir", "High Contrast", "Letterbox Frame", "Cinema Spotlights"],
    setupTime: "3 mins",
    perfectFor: "Film enthusiasts & dramatic love stories",
    features: ["Cinematic Letterboxing", "Film Grain Overlay", "Full Video Integration", "Masonry Gallery"],
    pagesIncluded: 5,
    animations: "Camera Lens Zoom",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  proposal: {
    id: "proposal",
    name: "Proposal Special",
    category: "Luxury Proposal",
    description: "Intimate champagne, warm candlelight, and an interactive proposal card for the big moment.",
    thumbnail: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80",
    vibe: "Intimate & Luxurious",
    atmosphere: "Champagne, candlelight, and forever. The most important moment.",
    badge: "Popular",
    tags: ["Proposal Ring", "Champagne Gold", "Candlelight", "Interactive Card"],
    setupTime: "2 mins",
    perfectFor: "Marriage proposals & grand romantic declarations",
    features: ["Interactive Proposal Card", "Champagne Sparkle FX", "Custom Countdown", "Background Audio"],
    pagesIncluded: 4,
    animations: "Ring Sparkle FX",
    performanceScore: 100,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  moonlight: {
    id: "moonlight",
    name: "Moonlight Promise",
    category: "Sapphire Night",
    description: "Midnight sapphire sky with glowing silver moonlight and celestial constellation particles.",
    thumbnail: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80",
    vibe: "Midnight Sapphire & Silver Glow",
    atmosphere: "A quiet midnight under glowing constellations and silver moonlight.",
    badge: "New",
    tags: ["Sapphire Blue", "Silver Moonlight", "Constellations", "Glowing Stars"],
    setupTime: "2 mins",
    perfectFor: "Night lovers & quiet romantic promises",
    features: ["Silver Moon FX", "Constellation Canvas", "Sapphire Gradient", "Interactive Story"],
    pagesIncluded: 4,
    animations: "Twinkling Constellations",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  golden: {
    id: "golden",
    name: "Golden Vows",
    category: "Regal Gold",
    description: "Opulent gold foil accents and timeless royal wedding editorial typography.",
    thumbnail: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    vibe: "Gilded Ivory & Regal Serif",
    atmosphere: "Opulent gold foil accents and timeless royal wedding elegance.",
    badge: "Featured",
    tags: ["Regal Gold", "Gilded Foil", "Ivory Accents", "Serif Typography"],
    setupTime: "2 mins",
    perfectFor: "Weddings, vows & golden jubilees",
    features: ["Gold Dust Particles", "Gilded Borders", "Vow Section", "Full Photo Gallery"],
    pagesIncluded: 4,
    animations: "Gold Shimmer Physics",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  sakura: {
    id: "sakura",
    name: "Sakura Bloom",
    category: "Cherry Blossom",
    description: "Gentle pink petals floating through spring breezes and warm pearl sunlight.",
    thumbnail: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=800&q=80",
    vibe: "Soft Cherry Blossom & Pearl",
    atmosphere: "Gentle pink petals floating through spring breezes and warm sunlight.",
    badge: "New",
    tags: ["Cherry Blossom", "Sakura Petals", "Soft Pink", "Pearl Warmth"],
    setupTime: "2 mins",
    perfectFor: "Spring romance & soft aesthetic memories",
    features: ["Floating Sakura Petals", "Soft Pink Canvas", "Poetry Cards", "Audio Track"],
    pagesIncluded: 4,
    animations: "Sakura Petal Breeze",
    performanceScore: 98,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
  eternal: {
    id: "eternal",
    name: "Eternal Hearts",
    category: "Crimson Passion",
    description: "Deep crimson waves and glowing heartbeat pulses that celebrate everlasting passion.",
    thumbnail: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
    vibe: "Deep Crimson & Radiant Ruby",
    atmosphere: "Passionate crimson waves and glowing heartbeats that last forever.",
    badge: "Popular",
    tags: ["Deep Crimson", "Heartbeat Pulse", "Ruby Red", "Romantic Cards"],
    setupTime: "2 mins",
    perfectFor: "Passionate lovers & milestone celebrations",
    features: ["Heartbeat Pulse FX", "Crimson Glow", "Love Timeline", "Music Player"],
    pagesIncluded: 4,
    animations: "Pulse Heartbeat Wave",
    performanceScore: 99,
    aiReady: true,
    responsive: true,
    seoReady: true,
    darkMode: true,
  },
};

export const TEMPLATE_CATEGORIES = [
  "All",
  "Cosmic Romance",
  "Classic Editorial",
  "Vintage Romance",
  "Ethereal Dream",
  "Cinematic Film",
  "Luxury Proposal",
  "Sapphire Night",
  "Regal Gold",
  "Cherry Blossom",
  "Crimson Passion",
];

export const TEMPLATE_LIST = Object.values(TEMPLATES_DATA);
